# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Campeonato de Kart' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods para Campeonato de Kart

  # Pods para Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  # Pods para Facebook 
  pod 'Bolts'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'

end
